# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [notifications, 100]
  - [http_request, 50]
  - [search_indexer, 30]
  - [medium, 10]
  - [mailer, 5]
  - [mailers, 5]
  - [default, 3]
:schedule:
  weekly_hot_topic_job:
    every: 1h
    class: WeeklyHotTopicJob
